### ISSUE TITLE
Couldn't able to delete the cookie

### ISSUE THREAD

**Issue by selvavalluvan** [martini-contrib/sessions#13]
Hello,

I was just trying the example code that you have given. I tried to delete the cookie by setting up MaxAge : -1. It seems that its not accepting the options. Below is my code.

package main

 import (
   "github.com/go-martini/martini"
   "github.com/martini-contrib/sessions"
   //"net/http"
   //"fmt"
   //"strconv"

 )

 func init() {
    m := martini.Classic()

```
store := sessions.NewCookieStore([]byte("secret123"))
m.Use(sessions.Sessions("my_session", store))

m.Get("/set", func(session sessions.Session) string {
    session.Set("hello", "world")
    return "OK"
})

m.Get("/get", func(session sessions.Session) string {
    v := session.Get("hello")
    if v == nil {
        return ""
    }
    return v.(string)
})

m.Get("/logout", func(session sessions.Session) {

    op:=sessions.Options{
          MaxAge: -1 ,
    }
    session.Options(op)

})
```

  m.Run()
 }

May I know if anything wrong with this.

**Comment by dougbarrett** [comment]
Not sure if you figured this out, but after I set `session.Options(op)` I executed `session.Clear()` and it worked for me.
